# Generated by Django 4.0.1 on 2022-01-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Individual', 'Individual'), ('Legal entity', 'Legal entity')], max_length=50, null=True)),
                ('full_name', models.CharField(max_length=150, null=True)),
                ('rank', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
