# Generated by Django 4.0.1 on 2022-01-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_registration_category_registration_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='field',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
